apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  nfsServerHostname: 10.1.10.7
  nfsPath: /opt/persistent
